<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>72d98015-3a9d-4580-aa7c-16e075631ed9</testSuiteGuid>
   <testCaseLink>
      <guid>99d99bb1-df50-4ce0-8fcc-daf788c967eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDriverTesting/TC_Parameterization_ForLoop</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bedd69ee-8653-44d2-9e62-b092d04bed4f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_facebookReg</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>bedd69ee-8653-44d2-9e62-b092d04bed4f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>a2dfb82b-1952-407e-9fd7-968508c1809a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bedd69ee-8653-44d2-9e62-b092d04bed4f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pwd</value>
         <variableId>1dc6ba97-f7bb-48bf-b7d5-c0caeeb4f518</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd8e7a08-4d2e-42ae-bf4f-5f44792b6544</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
