<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_run</name>
   <tag></tag>
   <elementGuidId>60b54e64-bb99-47de-8630-9a5a8e096879</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[normalize-space()='Run']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[normalize-space()='Run']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
